### ISSUE TITLE
AttributeError: 'TorInstance' object has no attribute 'get_requests_session'

### ISSUE THREAD

**Issue by UnlimitedChild** [SammyTheBEAST/TorDownloader#1]
Hello, 

Traceback (most recent call last):
  File "C:\VirtualEnv\PycharmProjects\pythonProject\venv\Lib\site-packages\tor_downloader\__main__.py", line 192, in <module>
    main()
  File "C:\VirtualEnv\PycharmProjects\pythonProject\venv\Lib\site-packages\tor_downloader\__main__.py", line 184, in main
    raise err
  File "C:\VirtualEnv\PycharmProjects\pythonProject\venv\Lib\site-packages\tor_downloader\__main__.py", line 154, in main
    downloader = FileDownloader(tor_instance=tor_instance, tor_port=CONFIG["socks_port"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VirtualEnv\PycharmProjects\pythonProject\venv\Lib\site-packages\tor_downloader\file_downloader.py", line 56, in __init__
    self.requests_session, self.session_num = self.tor_instance.get_requests_session()
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
**AttributeError: 'TorInstance' object has no attribute 'get_requests_session'**

Process finished with exit code 1

**Comment by Kevin-Deason** [comment]
You can change line 65 in [file_downloader.py](https://github.com/SammyTheBEAST/TorDownloader/blob/main/tor_downloader/file_downloader.py) to below:
`self.requests_session, self.session_num = self.tor_instance.get_session_with_number()`

Might work after that

**Comment by Ian-Costa18** [comment]
Thank you both for your interest in this project. @UnlimitedChild I believe you are running an outdated version of the module, please run `python -m pip install --upgrade tor_downloader` to update to the newest version. @Kevin-Deason you are correct that is the fix required for that version.

I have also just pushed an update to the script to fix other issues. I tested it myself and it worked, please let me know if you run into any more issues.
